# Generated by Django 4.2.14 on 2024-07-25 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ico', models.CharField(max_length=100)),
                ('dic', models.CharField(max_length=100)),
                ('link_google_maps', models.TextField(blank=True, null=True)),
                ('ic_dph', models.CharField(max_length=100)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.address')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.email')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.phone')),
            ],
        ),
    ]
