# Generated by Django 4.2.14 on 2024-07-18 10:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('home', models.CharField(blank=True, max_length=50, null=True)),
                ('about', models.CharField(blank=True, max_length=50, null=True)),
                ('services', models.CharField(blank=True, max_length=50, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('login', models.CharField(blank=True, max_length=50, null=True)),
                ('logout', models.CharField(blank=True, max_length=50, null=True)),
                ('register', models.CharField(blank=True, max_length=50, null=True)),
                ('profile', models.CharField(blank=True, max_length=50, null=True)),
                ('dashboard', models.CharField(blank=True, max_length=50, null=True)),
                ('admin', models.CharField(blank=True, max_length=50, null=True)),
                ('users', models.CharField(blank=True, max_length=50, null=True)),
                ('groups', models.CharField(blank=True, max_length=50, null=True)),
                ('permissions', models.CharField(blank=True, max_length=50, null=True)),
                ('settings', models.CharField(blank=True, max_length=50, null=True)),
                ('help', models.CharField(blank=True, max_length=50, null=True)),
                ('search', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('theme', models.CharField(blank=True, max_length=50, null=True)),
                ('light', models.CharField(blank=True, max_length=50, null=True)),
                ('dark', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
