# Generated by Django 4.2.14 on 2024-07-25 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('ico', models.CharField(max_length=100)),
                ('dic', models.CharField(max_length=100)),
                ('ic_dph', models.CharField(max_length=100)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.address')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.phone')),
            ],
        ),
    ]
