# Generated by Django 4.2.14 on 2024-07-25 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
        ('pages', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.email'),
        ),
    ]
