# Generated by Django 4.2.14 on 2024-07-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='link_google_maps',
            field=models.TextField(blank=True, null=True),
        ),
    ]
