# Generated by Django 4.2.14 on 2024-07-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='name',
        ),
        migrations.AlterField(
            model_name='photo',
            name='object_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
